name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive

      - name: Set up emsdk
        uses: emscripten-core/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: latest
          actions-cache-folder: .emsdk-cache

      - name: Set up pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build autoconf automake libtool pkg-config wget python3 golang-go

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Install Playwright browser
        run: pnpm test:install

    #   - name: Restore build cache
    #     id: build-cache
    #     uses: actions/cache@v5
    #     with:
    #       path: libcurl.js/client/build
    #       key: deps-${{ runner.os }}-${{ hashFiles('patches/**', 'tools/**', 'curl-impersonate/patches/**') }}
    #       restore-keys: |
    #         deps-${{ runner.os }}-

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test